language: go
matrix:
    include:
        - os: linux
          go: tip
        - os: linux
          go: 1.17.x
          env:
            - JS=1
        - os: osx
          go: tip
        - os: windows
          go: 1.17.x
#Added power jobs
        - os: linux
          go: 1.17.x
          arch: ppc64le
        - os: linux
          go: 1.17.x
          arch: ppc64le
          env:
            - JS=1
script: bash .travis.sh script
notifications:
  webhooks: https://coveralls.io/webhook
  email:
    on_success: never
    on_failure: change
