language: go
matrix:
    include:
        - os: linux
          go: tip
        - os: linux
          go: tip
          env:
            - JS=1
        - os: osx
          go: tip
        - os: windows
          go: 1.x
script: bash .travis.sh script
notifications:
  webhooks: https://coveralls.io/webhook
  email:
    on_success: never
    on_failure: change
