name: go test
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,  windows-latest, macos-latest]
    steps:
      - id: go-test
        uses: djherbis/actions/go-test@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coveralls_parallel: true
  buildjs:
    runs-on: ubuntu-latest
    steps:
      - id: go-test-js
        uses: djherbis/actions/go-test-js@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coveralls_parallel: true
  finish:
      needs: [build, buildjs]
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished
        run: |
          curl https://coveralls.io/webhook?repo_token=${{ secrets.coveralls }} -d "payload[build_num]=${{ github.sha }}&payload[status]=done"