name: go test
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,  windows-latest, macos-latest]
    steps:
      - id: go-test
        uses: djherbis/actions/go-test@main
        with:
          coveralls_parallel: true
  buildjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: go test
        env:
          GOOS: js
          GOARCH: wasm
          GO111MODULE: auto
        run: go test -covermode=count -coverprofile=profile.cov -exec="$(go env GOROOT)/misc/wasm/go_js_wasm_exec"
      - name: Send coverage
        env:
          COVERALLS_PARALLEL: true
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        if: github.event_name != 'pull_request'